-- Migration: Float → DECIMAL(19,4) pour tous les montants financiers

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "annualRevenue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "defaultVatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "creditLimit" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "outstandingAmount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "CustomerActivity" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "defaultVatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "salePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "salePriceIncludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "purchasePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "marginAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "marginRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "stockQuantity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "stockAlertThreshold" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "ItemPriceHistory" ALTER COLUMN "oldSalePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "newSalePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "oldPurchasePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "newPurchasePriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "oldVatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "newVatRate" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "ItemActivity" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Quote" ALTER COLUMN "subtotalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalDiscountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "globalDiscountValue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "shippingAmountExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "otherFeesExcludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "QuoteLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "unitPriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountValue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "vatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "subtotalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalDiscountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "amountPaid" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "amountDue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "globalDiscountValue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "shippingAmountExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "otherFeesExcludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "InvoiceLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "unitPriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountValue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "vatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "CreditNote" ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "CreditNoteLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "unitPriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "vatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "allocatedAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "unallocatedAmount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "PaymentAllocation" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Reminder" ALTER COLUMN "invoiceTotalIncludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "invoiceAmountPaid" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "invoiceAmountDue" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "Supplier" ALTER COLUMN "defaultVatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "outstandingAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalPurchasesAmount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "SupplierActivity" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "ExpenseCategory" ALTER COLUMN "defaultVatRate" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "SupplierInvoice" ALTER COLUMN "subtotalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalDiscountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "amountPaid" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "amountDue" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "defaultVatRate" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "SupplierInvoiceLine" ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "unitPriceExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "discountAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "vatRate" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalExcludingTax" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalVatAmount" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalIncludingTax" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "AccountingEntry" ALTER COLUMN "totalDebit" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "totalCredit" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "AccountingEntryLine" ALTER COLUMN "debit" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "credit" SET DATA TYPE DECIMAL(19,4),
ALTER COLUMN "taxRate" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "TaxRate" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(19,4);

-- AlterTable
ALTER TABLE "CurrencySetting" ALTER COLUMN "exchangeRateToDefault" SET DATA TYPE DECIMAL(19,4);

