export const ROLE_LABELS: Record<string, string> = {
  OWNER: "Propriétaire",
  ADMIN: "Administrateur",
  ACCOUNTANT: "Comptable",
  SALES: "Commercial",
  READ_ONLY: "Lecture seule",
};

export const MEMBER_STATUS_LABELS: Record<string, string> = {
  ACTIVE: "Actif",
  INVITED: "Invité",
  SUSPENDED: "Suspendu",
};

export const NUMBERING_TYPE_LABELS: Record<string, string> = {
  CUSTOMER: "Clients",
  SUPPLIER: "Fournisseurs",
  ITEM: "Articles",
  QUOTE: "Devis",
  INVOICE: "Factures",
  CREDIT_NOTE: "Avoirs",
  PAYMENT: "Règlements",
  REMINDER: "Relances",
  SUPPLIER_INVOICE: "Factures fournisseur",
  ACCOUNTING_ENTRY: "Écritures comptables",
};

export const RESET_PERIOD_LABELS: Record<string, string> = {
  NEVER: "Jamais",
  YEARLY: "Annuelle",
  MONTHLY: "Mensuelle",
};

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  DEMO_LOGIN: "Connexion (legacy)",
  DEMO_LOGOUT: "Déconnexion (legacy)",
  USER_LOGIN: "Connexion",
  USER_LOGOUT: "Déconnexion",
  ORGANIZATION_CREATED: "Organisation créée",
  ORGANIZATION_UPDATED: "Organisation modifiée",
  MEMBER_INVITED: "Membre invité",
  MEMBER_ROLE_UPDATED: "Rôle modifié",
  MEMBER_SUSPENDED: "Membre suspendu",
  MEMBER_REACTIVATED: "Membre réactivé",
  SETTINGS_UPDATED: "Paramètres modifiés",
  NUMBERING_UPDATED: "Numérotation modifiée",
  NUMBER_GENERATED: "Numéro généré",
  CUSTOMER_CREATED: "Client créé",
  CUSTOMER_UPDATED: "Client modifié",
  CUSTOMER_ARCHIVED: "Client archivé",
  CUSTOMER_REACTIVATED: "Client réactivé",
  CUSTOMER_CONTACT_CREATED: "Contact client créé",
  CUSTOMER_CONTACT_UPDATED: "Contact client modifié",
  CUSTOMER_CONTACT_DELETED: "Contact client supprimé",
  CUSTOMER_ADDRESS_CREATED: "Adresse client créée",
  CUSTOMER_ADDRESS_UPDATED: "Adresse client modifiée",
  CUSTOMER_ADDRESS_DELETED: "Adresse client supprimée",
  CUSTOMER_NOTE_CREATED: "Note client ajoutée",
  CUSTOMER_TAG_ASSIGNED: "Tag assigné",
  CUSTOMER_TAG_REMOVED: "Tag retiré",
  CUSTOMER_EXPORTED: "Export clients CSV",
  ITEM_CREATED: "Article créé",
  ITEM_UPDATED: "Article modifié",
  ITEM_ARCHIVED: "Article archivé",
  ITEM_REACTIVATED: "Article réactivé",
  ITEM_PRICE_UPDATED: "Prix article modifié",
  ITEM_TAG_ASSIGNED: "Tag article assigné",
  ITEM_TAG_REMOVED: "Tag article retiré",
  ITEM_CATEGORY_CREATED: "Catégorie créée",
  ITEM_EXPORTED: "Export catalogue CSV",
  QUOTE_CREATED: "Devis créé",
  QUOTE_UPDATED: "Devis modifié",
  QUOTE_SENT: "Devis envoyé",
  QUOTE_VIEWED: "Devis consulté",
  QUOTE_ACCEPTED: "Devis accepté",
  QUOTE_REFUSED: "Devis refusé",
  QUOTE_EXPIRED: "Devis expiré",
  QUOTE_CANCELLED: "Devis annulé",
  QUOTE_CONVERTED: "Devis converti en facture",
  QUOTE_ARCHIVED: "Devis archivé",
  QUOTE_REACTIVATED: "Devis réactivé",
  QUOTE_DUPLICATED: "Devis dupliqué",
  QUOTE_PDF_GENERATED: "PDF devis généré",
  QUOTE_EMAIL_SIMULATED: "Notification email devis",
  QUOTE_EXPORTED: "Export devis CSV",
  INVOICE_CREATED: "Facture créée",
  INVOICE_CREATED_FROM_QUOTE: "Facture créée depuis devis",
  INVOICE_UPDATED: "Facture modifiée",
  INVOICE_VALIDATED: "Facture validée",
  INVOICE_SENT: "Facture envoyée",
  INVOICE_EMAIL_SIMULATED: "Notification email facture",
  INVOICE_PDF_GENERATED: "PDF facture généré",
  INVOICE_MARKED_OVERDUE: "Facture marquée en retard",
  INVOICE_MARKED_PAID_PLACEHOLDER: "Facture marquée comme payée",
  INVOICE_PARTIAL_PAYMENT_PLACEHOLDER: "Paiement partiel enregistré",
  INVOICE_CANCELLED: "Facture annulée",
  INVOICE_CREDITED: "Facture créditée",
  INVOICE_ARCHIVED: "Facture archivée",
  INVOICE_REACTIVATED: "Facture réactivée",
  INVOICE_DUPLICATED: "Facture dupliquée",
  INVOICE_EXPORTED: "Export factures CSV",
  CREDIT_NOTE_CREATED: "Avoir créé",
  CREDIT_NOTE_CANCELLED: "Avoir annulé",
  PAYMENT_CREATED: "Paiement créé",
  PAYMENT_UPDATED: "Paiement modifié",
  PAYMENT_ALLOCATED: "Paiement alloué",
  PAYMENT_DEALLOCATED: "Paiement désalloué",
  PAYMENT_CANCELLED: "Paiement annulé",
  PAYMENT_RECEIPT_GENERATED: "Reçu de paiement généré",
  PAYMENT_RECEIPT_EMAIL_SIMULATED: "Notification email reçu",
  PAYMENT_EXPORTED: "Export paiements CSV",
  INVOICE_PAYMENT_RECEIVED: "Paiement facture reçu",
  INVOICE_PAYMENT_CANCELLED: "Paiement facture annulé",
  CUSTOMER_OUTSTANDING_RECALCULATED: "Encours client recalculé",
  REMINDER_CREATED: "Relance créée",
  REMINDER_UPDATED: "Relance modifiée",
  REMINDER_EMAIL_SIMULATED: "Relance envoyée",
  REMINDER_BULK_EMAIL_SIMULATED: "Relances groupées envoyées",
  REMINDER_CANCELLED: "Relance annulée",
  REMINDER_TEMPLATE_CREATED: "Modèle de relance créé",
  REMINDER_TEMPLATE_UPDATED: "Modèle de relance modifié",
  REMINDER_TEMPLATE_DISABLED: "Modèle de relance désactivé",
  REMINDER_NOTE_CREATED: "Note de recouvrement ajoutée",
  REMINDER_EXPORTED: "Export relances CSV",
  REMINDER_HISTORY_EXPORTED: "Export historique relances CSV",
  COLLECTION_PAUSED: "Recouvrement suspendu",
  COLLECTION_RESUMED: "Recouvrement repris",
  INVOICE_DISPUTED: "Facture en litige",
  INVOICE_DISPUTE_RESOLVED: "Litige résolu",
  PROMISED_PAYMENT_DATE_SET: "Promesse de paiement enregistrée",
  INVOICE_REMINDER_SENT: "Relance facture envoyée",
  CUSTOMER_COLLECTION_NOTE_CREATED: "Note recouvrement client",
  SUPPLIER_CREATED: "Fournisseur créé",
  SUPPLIER_UPDATED: "Fournisseur modifié",
  SUPPLIER_ARCHIVED: "Fournisseur archivé",
  SUPPLIER_REACTIVATED: "Fournisseur réactivé",
  SUPPLIER_CONTACT_CREATED: "Contact fournisseur créé",
  SUPPLIER_CONTACT_UPDATED: "Contact fournisseur modifié",
  SUPPLIER_CONTACT_DELETED: "Contact fournisseur supprimé",
  SUPPLIER_ADDRESS_CREATED: "Adresse fournisseur créée",
  SUPPLIER_ADDRESS_UPDATED: "Adresse fournisseur modifiée",
  SUPPLIER_ADDRESS_DELETED: "Adresse fournisseur supprimée",
  SUPPLIER_BANK_ACCOUNT_CREATED: "Compte bancaire fournisseur créé",
  SUPPLIER_BANK_ACCOUNT_UPDATED: "Compte bancaire fournisseur modifié",
  SUPPLIER_BANK_ACCOUNT_DISABLED: "Compte bancaire fournisseur désactivé",
  SUPPLIER_BANK_ACCOUNT_SET_DEFAULT: "Compte bancaire par défaut défini",
  SUPPLIER_NOTE_CREATED: "Note fournisseur ajoutée",
  SUPPLIER_TAG_ASSIGNED: "Tag fournisseur assigné",
  SUPPLIER_TAG_REMOVED: "Tag fournisseur retiré",
  SUPPLIER_CATEGORY_CREATED: "Catégorie fournisseur créée",
  SUPPLIER_EXPORTED: "Export fournisseurs CSV",
  SUPPLIER_INVOICE_CREATED: "Facture fournisseur créée",
  SUPPLIER_INVOICE_UPDATED: "Facture fournisseur modifiée",
  SUPPLIER_INVOICE_VALIDATED: "Facture fournisseur validée",
  SUPPLIER_INVOICE_CANCELLED: "Facture fournisseur annulée",
  SUPPLIER_INVOICE_ARCHIVED: "Facture fournisseur archivée",
  SUPPLIER_INVOICE_REACTIVATED: "Facture fournisseur réactivée",
  SUPPLIER_INVOICE_MARKED_PAID_PLACEHOLDER: "Facture fournisseur marquée payée",
  SUPPLIER_INVOICE_PARTIAL_PAYMENT_PLACEHOLDER: "Paiement partiel fournisseur enregistré",
  SUPPLIER_INVOICE_MARKED_OVERDUE: "Facture fournisseur marquée en retard",
  SUPPLIER_INVOICE_ATTACHMENT_ADDED: "Pièce jointe facture fournisseur ajoutée",
  SUPPLIER_INVOICE_ATTACHMENT_DELETED: "Pièce jointe facture fournisseur supprimée",
  SUPPLIER_INVOICE_NOTE_CREATED: "Note facture fournisseur ajoutée",
  SUPPLIER_INVOICE_EXPORTED: "Export factures fournisseurs CSV",
  EXPENSE_CATEGORY_CREATED: "Catégorie de dépense créée",
  ACCOUNTING_ACCOUNT_CREATED: "Compte comptable créé",
  ACCOUNTING_ACCOUNT_UPDATED: "Compte comptable modifié",
  ACCOUNTING_ACCOUNT_DISABLED: "Compte comptable désactivé",
  ACCOUNTING_JOURNAL_CREATED: "Journal comptable créé",
  ACCOUNTING_JOURNAL_UPDATED: "Journal comptable modifié",
  ACCOUNTING_ENTRY_CREATED: "Écriture comptable créée",
  ACCOUNTING_ENTRY_UPDATED: "Écriture comptable modifiée",
  ACCOUNTING_ENTRY_VALIDATED: "Écriture comptable validée",
  ACCOUNTING_ENTRY_CANCELLED: "Écriture comptable annulée",
  ACCOUNTING_ENTRY_DUPLICATED: "Écriture comptable dupliquée",
  ACCOUNTING_ENTRY_GENERATED_FROM_CUSTOMER_INVOICE: "Écriture générée depuis facture client",
  ACCOUNTING_ENTRY_GENERATED_FROM_CUSTOMER_PAYMENT: "Écriture générée depuis paiement client",
  ACCOUNTING_ENTRY_GENERATED_FROM_SUPPLIER_INVOICE: "Écriture générée depuis facture fournisseur",
  ACCOUNTING_MISSING_ENTRIES_GENERATED: "Écritures manquantes générées",
  ACCOUNTING_ENTRIES_EXPORTED: "Export écritures comptables CSV",
  ACCOUNTING_LEDGER_EXPORTED: "Export grand livre CSV",
  ACCOUNTING_TRIAL_BALANCE_EXPORTED: "Export balance CSV",
  ACCOUNTING_VAT_SUMMARY_EXPORTED: "Export synthèse TVA CSV",
};
