import {
  AuditAction,
  NumberingResetPeriod,
  NumberingSequenceType,
  PermissionKey,
  SystemRole,
} from "@prisma/client";

export const ALL_PERMISSIONS: PermissionKey[] = [
  "ORGANIZATION_READ",
  "ORGANIZATION_UPDATE",
  "MEMBERS_READ",
  "MEMBERS_INVITE",
  "MEMBERS_UPDATE",
  "MEMBERS_SUSPEND",
  "SETTINGS_READ",
  "SETTINGS_UPDATE",
  "NUMBERING_READ",
  "NUMBERING_UPDATE",
  "AUDIT_LOG_READ",
  "DASHBOARD_READ",
  "DASHBOARD_EXPORT",
  "CUSTOMERS_READ",
  "CUSTOMERS_CREATE",
  "CUSTOMERS_UPDATE",
  "CUSTOMERS_DELETE",
  "ITEMS_READ",
  "ITEMS_CREATE",
  "ITEMS_UPDATE",
  "ITEMS_DELETE",
  "QUOTES_READ",
  "QUOTES_CREATE",
  "QUOTES_UPDATE",
  "QUOTES_VALIDATE",
  "QUOTES_DELETE",
  "INVOICES_READ",
  "INVOICES_CREATE",
  "INVOICES_UPDATE",
  "INVOICES_VALIDATE",
  "INVOICES_CANCEL",
  "PAYMENTS_READ",
  "PAYMENTS_CREATE",
  "PAYMENTS_UPDATE",
  "PAYMENTS_CANCEL",
  "PAYMENTS_EXPORT",
  "REMINDERS_READ",
  "REMINDERS_CREATE",
  "REMINDERS_UPDATE",
  "REMINDERS_SEND",
  "REMINDERS_CANCEL",
  "REMINDERS_EXPORT",
  "REMINDER_TEMPLATES_READ",
  "REMINDER_TEMPLATES_UPDATE",
  "SUPPLIERS_READ",
  "SUPPLIERS_CREATE",
  "SUPPLIERS_UPDATE",
  "SUPPLIERS_DELETE",
  "SUPPLIERS_EXPORT",
  "SUPPLIERS_BANK_DETAILS_UPDATE",
  "SUPPLIER_INVOICES_READ",
  "SUPPLIER_INVOICES_CREATE",
  "SUPPLIER_INVOICES_UPDATE",
  "SUPPLIER_INVOICES_VALIDATE",
  "SUPPLIER_INVOICES_CANCEL",
  "SUPPLIER_INVOICES_EXPORT",
  "ACCOUNTING_READ",
  "ACCOUNTING_EXPORT",
  "ACCOUNTING_CREATE",
  "ACCOUNTING_UPDATE",
  "ACCOUNTING_VALIDATE",
  "ACCOUNTING_CANCEL",
  "ACCOUNTING_SETTINGS_UPDATE",
  "EXPORTS_READ",
  "EXPORTS_CREATE",
  "EXPORTS_DOWNLOAD",
  "DOCUMENTS_READ",
  "DOCUMENTS_CREATE",
  "DOCUMENTS_ARCHIVE",
  "DOCUMENT_TEMPLATES_READ",
  "DOCUMENT_TEMPLATES_UPDATE",
  "ADVANCED_SETTINGS_READ",
  "ADVANCED_SETTINGS_UPDATE",
  "GLOBAL_SEARCH_USE",
  "SEARCH_HISTORY_READ",
  "SEARCH_HISTORY_CLEAR",
  "FAVORITES_READ",
  "FAVORITES_UPDATE",
];

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  ORGANIZATION_READ: "Lire l'organisation",
  ORGANIZATION_UPDATE: "Modifier l'organisation",
  MEMBERS_READ: "Lire les membres",
  MEMBERS_INVITE: "Inviter des membres",
  MEMBERS_UPDATE: "Modifier les membres",
  MEMBERS_SUSPEND: "Suspendre des membres",
  SETTINGS_READ: "Lire les paramètres",
  SETTINGS_UPDATE: "Modifier les paramètres",
  NUMBERING_READ: "Lire la numérotation",
  NUMBERING_UPDATE: "Modifier la numérotation",
  AUDIT_LOG_READ: "Lire le journal d'audit",
  DASHBOARD_READ: "Lire le tableau de bord",
  DASHBOARD_EXPORT: "Exporter le tableau de bord",
  CUSTOMERS_READ: "Lire les clients",
  CUSTOMERS_CREATE: "Créer des clients",
  CUSTOMERS_UPDATE: "Modifier les clients",
  CUSTOMERS_DELETE: "Supprimer les clients",
  ITEMS_READ: "Lire les articles",
  ITEMS_CREATE: "Créer des articles",
  ITEMS_UPDATE: "Modifier les articles",
  ITEMS_DELETE: "Supprimer les articles",
  QUOTES_READ: "Lire les devis",
  QUOTES_CREATE: "Créer des devis",
  QUOTES_UPDATE: "Modifier les devis",
  QUOTES_VALIDATE: "Valider des devis",
  QUOTES_DELETE: "Supprimer des devis",
  INVOICES_READ: "Lire les factures",
  INVOICES_CREATE: "Créer des factures",
  INVOICES_UPDATE: "Modifier les factures",
  INVOICES_VALIDATE: "Valider des factures",
  INVOICES_CANCEL: "Annuler des factures",
  PAYMENTS_READ: "Lire les paiements",
  PAYMENTS_CREATE: "Créer des paiements",
  PAYMENTS_UPDATE: "Modifier les paiements",
  PAYMENTS_CANCEL: "Annuler des paiements",
  PAYMENTS_EXPORT: "Exporter les paiements",
  REMINDERS_READ: "Lire les relances",
  REMINDERS_CREATE: "Créer des relances",
  REMINDERS_UPDATE: "Modifier le recouvrement",
  REMINDERS_SEND: "Envoyer des relances",
  REMINDERS_CANCEL: "Annuler des relances",
  REMINDERS_EXPORT: "Exporter les relances",
  REMINDER_TEMPLATES_READ: "Lire les modèles de relance",
  REMINDER_TEMPLATES_UPDATE: "Modifier les modèles de relance",
  SUPPLIERS_READ: "Lire les fournisseurs",
  SUPPLIERS_CREATE: "Créer des fournisseurs",
  SUPPLIERS_UPDATE: "Modifier les fournisseurs",
  SUPPLIERS_DELETE: "Archiver des fournisseurs",
  SUPPLIERS_EXPORT: "Exporter les fournisseurs",
  SUPPLIERS_BANK_DETAILS_UPDATE: "Modifier les coordonnées bancaires fournisseurs",
  SUPPLIER_INVOICES_READ: "Lire les factures fournisseurs",
  SUPPLIER_INVOICES_CREATE: "Créer des factures fournisseurs",
  SUPPLIER_INVOICES_UPDATE: "Modifier les factures fournisseurs",
  SUPPLIER_INVOICES_VALIDATE: "Valider des factures fournisseurs",
  SUPPLIER_INVOICES_CANCEL: "Annuler des factures fournisseurs",
  SUPPLIER_INVOICES_EXPORT: "Exporter les factures fournisseurs",
  ACCOUNTING_READ: "Lire la comptabilité",
  ACCOUNTING_EXPORT: "Exporter la comptabilité",
  ACCOUNTING_CREATE: "Créer des écritures comptables",
  ACCOUNTING_UPDATE: "Modifier la comptabilité",
  ACCOUNTING_VALIDATE: "Valider des écritures comptables",
  ACCOUNTING_CANCEL: "Annuler des écritures comptables",
  ACCOUNTING_SETTINGS_UPDATE: "Gérer le plan comptable et les journaux",
  EXPORTS_READ: "Lire le centre d'exports",
  EXPORTS_CREATE: "Lancer des exports",
  EXPORTS_DOWNLOAD: "Télécharger des exports",
  DOCUMENTS_READ: "Lire la bibliothèque documentaire",
  DOCUMENTS_CREATE: "Créer des documents",
  DOCUMENTS_ARCHIVE: "Archiver des documents",
  DOCUMENT_TEMPLATES_READ: "Lire les modèles de documents",
  DOCUMENT_TEMPLATES_UPDATE: "Gérer les modèles de documents",
  ADVANCED_SETTINGS_READ: "Lire les paramètres avancés",
  ADVANCED_SETTINGS_UPDATE: "Modifier les paramètres avancés",
  GLOBAL_SEARCH_USE: "Utiliser la recherche globale",
  SEARCH_HISTORY_READ: "Voir l'historique de recherche",
  SEARCH_HISTORY_CLEAR: "Effacer l'historique de recherche",
  FAVORITES_READ: "Voir les favoris",
  FAVORITES_UPDATE: "Gérer les favoris",
};

export const ROLE_PERMISSIONS: Record<SystemRole, PermissionKey[]> = {
  OWNER: ALL_PERMISSIONS,
  ADMIN: ALL_PERMISSIONS,
  ACCOUNTANT: [
    "ORGANIZATION_READ",
    "SETTINGS_READ",
    "NUMBERING_READ",
    "AUDIT_LOG_READ",
    "DASHBOARD_READ",
    "DASHBOARD_EXPORT",
    "CUSTOMERS_READ",
    "ITEMS_READ",
    "QUOTES_READ",
    "INVOICES_READ",
    "PAYMENTS_READ",
    "PAYMENTS_CREATE",
    "PAYMENTS_UPDATE",
    "PAYMENTS_CANCEL",
    "PAYMENTS_EXPORT",
    "REMINDERS_READ",
    "REMINDERS_CREATE",
    "REMINDERS_UPDATE",
    "REMINDERS_SEND",
    "REMINDERS_CANCEL",
    "REMINDERS_EXPORT",
    "REMINDER_TEMPLATES_READ",
    "REMINDER_TEMPLATES_UPDATE",
    "SUPPLIERS_READ",
    "SUPPLIERS_CREATE",
    "SUPPLIERS_UPDATE",
    "SUPPLIERS_EXPORT",
    "SUPPLIERS_BANK_DETAILS_UPDATE",
    "SUPPLIER_INVOICES_READ",
    "SUPPLIER_INVOICES_CREATE",
    "SUPPLIER_INVOICES_UPDATE",
    "SUPPLIER_INVOICES_VALIDATE",
    "SUPPLIER_INVOICES_CANCEL",
    "SUPPLIER_INVOICES_EXPORT",
    "ACCOUNTING_READ",
    "ACCOUNTING_EXPORT",
    "ACCOUNTING_CREATE",
    "ACCOUNTING_UPDATE",
    "ACCOUNTING_VALIDATE",
    "ACCOUNTING_CANCEL",
    "ACCOUNTING_SETTINGS_UPDATE",
    "EXPORTS_READ",
    "EXPORTS_CREATE",
    "EXPORTS_DOWNLOAD",
    "DOCUMENTS_READ",
    "DOCUMENTS_CREATE",
    "DOCUMENT_TEMPLATES_READ",
    "ADVANCED_SETTINGS_READ",
    "ADVANCED_SETTINGS_UPDATE",
    "GLOBAL_SEARCH_USE",
    "SEARCH_HISTORY_READ",
    "SEARCH_HISTORY_CLEAR",
    "FAVORITES_READ",
    "FAVORITES_UPDATE",
  ],
  SALES: [
    "ORGANIZATION_READ",
    "SETTINGS_READ",
    "DASHBOARD_READ",
    "EXPORTS_READ",
    "EXPORTS_CREATE",
    "EXPORTS_DOWNLOAD",
    "DOCUMENTS_READ",
    "DOCUMENTS_CREATE",
    "DOCUMENT_TEMPLATES_READ",
    "CUSTOMERS_READ",
    "CUSTOMERS_CREATE",
    "CUSTOMERS_UPDATE",
    "ITEMS_READ",
    "ITEMS_CREATE",
    "ITEMS_UPDATE",
    "QUOTES_READ",
    "QUOTES_CREATE",
    "QUOTES_UPDATE",
    "QUOTES_VALIDATE",
    "INVOICES_READ",
    "INVOICES_CREATE",
    "INVOICES_UPDATE",
    "PAYMENTS_READ",
    "PAYMENTS_CREATE",
    "PAYMENTS_EXPORT",
    "REMINDERS_READ",
    "REMINDERS_CREATE",
    "REMINDERS_SEND",
    "REMINDERS_EXPORT",
    "REMINDER_TEMPLATES_READ",
    "ADVANCED_SETTINGS_READ",
    "ADVANCED_SETTINGS_UPDATE",
    "GLOBAL_SEARCH_USE",
    "SEARCH_HISTORY_READ",
    "SEARCH_HISTORY_CLEAR",
    "FAVORITES_READ",
    "FAVORITES_UPDATE",
  ],
  READ_ONLY: [
    "ORGANIZATION_READ",
    "SETTINGS_READ",
    "DASHBOARD_READ",
    "EXPORTS_READ",
    "DOCUMENTS_READ",
    "DOCUMENT_TEMPLATES_READ",
    "CUSTOMERS_READ",
    "ITEMS_READ",
    "QUOTES_READ",
    "INVOICES_READ",
    "PAYMENTS_READ",
    "REMINDERS_READ",
    "REMINDER_TEMPLATES_READ",
    "SUPPLIERS_READ",
    "SUPPLIER_INVOICES_READ",
    "ACCOUNTING_READ",
    "ADVANCED_SETTINGS_READ",
    "GLOBAL_SEARCH_USE",
    "SEARCH_HISTORY_READ",
    "FAVORITES_READ",
    "FAVORITES_UPDATE",
  ],
};

export type SessionUser = {
  id: string;
  email: string;
  name: string;
  organizationId: string;
  roleKey: SystemRole;
  permissions: PermissionKey[];
};

export function hasPermission(
  user: Pick<SessionUser, "permissions">,
  permission: PermissionKey,
): boolean {
  return user.permissions.includes(permission);
}

export function requirePermission(
  user: Pick<SessionUser, "permissions">,
  permission: PermissionKey,
): void {
  if (!hasPermission(user, permission)) {
    throw new Error(`Permission refusée : ${permission}`);
  }
}

export function getPermissionsForRole(roleKey: SystemRole): PermissionKey[] {
  return ROLE_PERMISSIONS[roleKey];
}

export {
  AuditAction,
  NumberingResetPeriod,
  NumberingSequenceType,
  PermissionKey,
  SystemRole,
};
